### ISSUE TITLE
Not compatible with Nigtly

### ISSUE THREAD

**Issue by Vednier** [prefiks/u2f4moz#11]
Upon installation in Nightly (linux 64bit) all i get is
console.error: u2f: 
Object
    - _errorType = TypeError
    - message = can't redefine non-configurable property "u2f"
    - fileName = 
    - lineNumber = 0
    - stack = 
    - name = TypeError
Ofc, there is always Error 1 on U2F demo test

**Comment by prefiks** [comment]
That warning is to some degree expected, code on that page do know only on how to talk to implementation of u2f on chrome, and overwrites window.u2f object without first checking if there is one already available. I made that property not modifiable, so it wouldn't be overwritten by webpage version that only know how to work with chrome. Even with that warning it should work (and the fact that you getting error 1 signals that you probably u2f object from extension). I will probably remove that locking when pages will start have better detection code.

Now reason why you are getting error 1 and not correct response is from browser code not being able to talk to module that is responsible for usb communication, or because that module didn't recognize your device. Could you tell me what device do you have?

There is also this point that you must have your device plugged in before you initiate u2f operation, was that the case when you were testing?

**Comment by Vednier** [comment]
I use NyperFIDO U2F token (with button). I already added udev rules and checked it with u2f-test
Checking device HyperFIDO Token.
Usage: 1 UsagePage: f1d0.
USB send: 00ffffffff8600080807060504030201000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
USB write returned 65
now trying with timeout 2
now trying with timeout 4
USB read rc read 64
USB recv: ffffffff860011080706050403020100000001020100010100000000000000000000000000000000000000000000000000000000000000000000000000000000
device /dev/hidraw5 discovered as 'HyperFIDO Token'
  version (Interface, Major, Minor, Build): 2, 1, 0, 0  capFlags: 1
It should be available for Firefox.

**Comment by prefiks** [comment]
Yes, looks like your device should be able to work, but it doesn't =/

In next version i am adding more checks to both usb module and to browser code so hopefully it will help narrowing down what's happening with your device.

**Comment by prefiks** [comment]
New version 0.0.3 was published, it has changed how device communication is handled, and this fixed issue with some devices, so hopefully this will also help in your case. It also produces better messages in case of errors (they will be shown in webrowser consoie on page where u2f check was initiated), so in case of problems it may also help finding out whats happening.

**Comment by Vednier** [comment]
Ok, i have tried new, 0.0.3 version - no change. Still Exception: FIDO Client error: 1 (OTHER ERROR)
In console i see
TypeError: ({register:function register() {
    [native code]
}, sign:function sign() {
    [native code]
}}) is not extensible
in u2f-api.js:23:1

**Comment by prefiks** [comment]
Would be you able to send me logs from this program: http://prefiks.org/u2f4moz/linux64/u2f-reg-test, it will try to start register operation on your token, and dump all usb traffic to console.

**Comment by Vednier** [comment]
No problem except that this app crashed in the end of test
Checking device HyperFIDO Token.
Usage: 1 UsagePage: f1d0.
USB send: 00ffffffff8600080807060504030201000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
USB write returned 65
now trying with timeout 2
now trying with timeout 4
USB read rc read 64
USB recv: ffffffff86001108070605040302010000000a020100010100000000000000000000000000000000000000000000000000000000000000000000000000000000
device /dev/hidraw5 discovered as 'HyperFIDO Token'
  version (Interface, Major, Minor, Build): 2, 1, 0, 0  capFlags: 1
Checking device USB Receiver.
Usage: 2 UsagePage: 1.
Checking device USB Receiver.
Usage: 2 UsagePage: 1.
Checking device USB Receiver.
Usage: 1 UsagePage: ff00.
Checking device USB-compliant keyboard.
Usage: 0 UsagePage: 0.
Checking device USB-compliant keyboard.
Usage: 0 UsagePage: 0.
JSON: { "challenge": "zLA9a6ifD28iWXgM9ka1MIf55OGHPP-PD8jdvCPKQVw", "version": "U2F_V2", "appId": "http:\/\/test.com" }
JSON challenge URL-B64: zLA9a6ifD28iWXgM9ka1MIf55OGHPP-PD8jdvCPKQVw
client data: { "challenge": "zLA9a6ifD28iWXgM9ka1MIf55OGHPP-PD8jdvCPKQVw", "origin": "http:\/\/test.com", "typ": "navigator.id.finishEnrollment" }
JSON: { "challenge": "zLA9a6ifD28iWXgM9ka1MIf55OGHPP-PD8jdvCPKQVw", "version": "U2F_V2", "appId": "http:\/\/test.com" }
JSON app_id http://test.com
USB send: 000000000a83004700010300000040021102815a1307551dcbc4764b21b4c4380a8129cd26df0d0e6f9fa6d03e518a8b408a0c7163fdfff06ced3e80d7d2b3ac
USB write returned 65
USB send: 000000000a00db900905c4783c28295b8c9961650000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
USB write returned 65
now trying with timeout 2
now trying with timeout 4
USB read rc read 64
USB recv: 0000000a83000267000300000040021102815a1307551dcbc4764b21b4c4380a8129cd26df0d0e6f9fa6d03e518a8b408a0c7163fdfff06ced3e80d7d2b3acd9
USB data (len 2): 6700
Ошибка сегментирования (сделан дамп памяти)

**Comment by prefiks** [comment]
Could you also check this command: http://prefiks.org/u2f4moz/linux64/u2f-reg-test2?

**Comment by Vednier** [comment]
Yes, pretty much similar result
Checking device HyperFIDO Token.
Usage: 1 UsagePage: f1d0.
USB send: 00ffffffff8600080807060504030201000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
USB write returned 65
now trying with timeout 2
now trying with timeout 4
USB read rc read 64
USB recv: ffffffff86001108070605040302010000000d020100010100000000000000000000000000000000000000000000000000000000000000000000000000000000
device /dev/hidraw5 discovered as 'HyperFIDO Token'
  version (Interface, Major, Minor, Build): 2, 1, 0, 0  capFlags: 1
Checking device USB Receiver.
Usage: 2 UsagePage: 1.
Checking device USB Receiver.
Usage: 2 UsagePage: 1.
Checking device USB Receiver.
Usage: 1 UsagePage: ff00.
Checking device USB-compliant keyboard.
Usage: 0 UsagePage: 0.
Checking device USB-compliant keyboard.
Usage: 0 UsagePage: 0.
JSON: { "challenge": "zLA9a6ifD28iWXgM9ka1MIf55OGHPP-PD8jdvCPKQVw", "version": "U2F_V2", "appId": "http:\/\/test.com" }
JSON challenge URL-B64: zLA9a6ifD28iWXgM9ka1MIf55OGHPP-PD8jdvCPKQVw
client data: { "challenge": "zLA9a6ifD28iWXgM9ka1MIf55OGHPP-PD8jdvCPKQVw", "origin": "http:\/\/test.com", "typ": "navigator.id.finishEnrollment" }
JSON: { "challenge": "zLA9a6ifD28iWXgM9ka1MIf55OGHPP-PD8jdvCPKQVw", "version": "U2F_V2", "appId": "http:\/\/test.com" }
JSON app_id http://test.com
USB send: 000000000d83004700010000000040021102815a1307551dcbc4764b21b4c4380a8129cd26df0d0e6f9fa6d03e518a8b408a0c7163fdfff06ced3e80d7d2b3ac
USB write returned 65
USB send: 000000000d00db900905c4783c28295b8c9961650000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
USB write returned 65
now trying with timeout 2
now trying with timeout 4
USB read rc read 64
USB recv: 0000000d83000267000000000040021102815a1307551dcbc4764b21b4c4380a8129cd26df0d0e6f9fa6d03e518a8b408a0c7163fdfff06ced3e80d7d2b3acd9
USB data (len 2): 6700
Ошибка сегментирования (сделан дамп памяти)
(never purchase cheap stuff on Amazon again...)

**Comment by prefiks** [comment]
Ok, another try please: http://prefiks.org/u2f4moz/linux64/u2f-reg-test3 i didn't found in specification what 6700 code could mean, but in this version, i made it act as "waiting for button press", let see if this help at all.

**Comment by Vednier** [comment]
Sorry for waiting. I tried reg-test3. There was long delay during test. but token wasnt blinking not even once. After around 10s of waiting application exit
Checking device HyperFIDO Token.
Usage: 1 UsagePage: f1d0.
USB send: 00ffffffff8600080807060504030201000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
USB write returned 65
now trying with timeout 2
now trying with timeout 4
USB read rc read 64
USB recv: ffffffff860011080706050403020100000003020100010100000000000000000000000000000000000000000000000000000000000000000000000000000000
device /dev/hidraw5 discovered as 'HyperFIDO Token'
  version (Interface, Major, Minor, Build): 2, 1, 0, 0  capFlags: 1
Checking device USB Receiver.
Usage: 2 UsagePage: 1.
Checking device USB Receiver.
Usage: 2 UsagePage: 1.
Checking device USB Receiver.
Usage: 1 UsagePage: ff00.
Checking device USB-compliant keyboard.
Usage: 0 UsagePage: 0.
Checking device USB-compliant keyboard.
Usage: 0 UsagePage: 0.
JSON: { "challenge": "zLA9a6ifD28iWXgM9ka1MIf55OGHPP-PD8jdvCPKQVw", "version": "U2F_V2", "appId": "http:\/\/test.com" }
JSON challenge URL-B64: zLA9a6ifD28iWXgM9ka1MIf55OGHPP-PD8jdvCPKQVw
client data: { "challenge": "zLA9a6ifD28iWXgM9ka1MIf55OGHPP-PD8jdvCPKQVw", "origin": "http:\/\/test.com", "typ": "navigator.id.finishEnrollment" }
JSON: { "challenge": "zLA9a6ifD28iWXgM9ka1MIf55OGHPP-PD8jdvCPKQVw", "version": "U2F_V2", "appId": "http:\/\/test.com" }
JSON app_id http://test.com
USB send: 000000000383004700010300000040021102815a1307551dcbc4764b21b4c4380a8129cd26df0d0e6f9fa6d03e518a8b408a0c7163fdfff06ced3e80d7d2b3ac
USB write returned 65
USB send: 000000000300db900905c4783c28295b8c9961650000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
USB write returned 65
now trying with timeout 2
now trying with timeout 4
USB read rc read 64
USB recv: 0000000383000267000300000040021102815a1307551dcbc4764b21b4c4380a8129cd26df0d0e6f9fa6d03e518a8b408a0c7163fdfff06ced3e80d7d2b3acd9
USB data (len 2): 6700
USB send: 000000000383004700010300000040021102815a1307551dcbc4764b21b4c4380a8129cd26df0d0e6f9fa6d03e518a8b408a0c7163fdfff06ced3e80d7d2b3ac
USB write returned 65
USB send: 000000000300db900905c4783c28295b8c9961650000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
USB write returned 65
now trying with timeout 2
now trying with timeout 4
USB read rc read 64
USB recv: 0000000383000267000300000040021102815a1307551dcbc4764b21b4c4380a8129cd26df0d0e6f9fa6d03e518a8b408a0c7163fdfff06ced3e80d7d2b3acd9
USB data (len 2): 6700
USB send: 000000000383004700010300000040021102815a1307551dcbc4764b21b4c4380a8129cd26df0d0e6f9fa6d03e518a8b408a0c7163fdfff06ced3e80d7d2b3ac
USB write returned 65
USB send: 000000000300db900905c4783c28295b8c9961650000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
USB write returned 65
now trying with timeout 2
now trying with timeout 4
USB read rc read 64
USB recv: 0000000383000267000300000040021102815a1307551dcbc4764b21b4c4380a8129cd26df0d0e6f9fa6d03e518a8b408a0c7163fdfff06ced3e80d7d2b3acd9
USB data (len 2): 6700
USB send: 000000000383004700010300000040021102815a1307551dcbc4764b21b4c4380a8129cd26df0d0e6f9fa6d03e518a8b408a0c7163fdfff06ced3e80d7d2b3ac
USB write returned 65
USB send: 000000000300db900905c4783c28295b8c9961650000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
USB write returned 65
now trying with timeout 2
now trying with timeout 4
USB read rc read 64
USB recv: 0000000383000267000300000040021102815a1307551dcbc4764b21b4c4380a8129cd26df0d0e6f9fa6d03e518a8b408a0c7163fdfff06ced3e80d7d2b3acd9
USB data (len 2): 6700
USB send: 000000000383004700010300000040021102815a1307551dcbc4764b21b4c4380a8129cd26df0d0e6f9fa6d03e518a8b408a0c7163fdfff06ced3e80d7d2b3ac
USB write returned 65
USB send: 000000000300db900905c4783c28295b8c9961650000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
USB write returned 65
now trying with timeout 2
now trying with timeout 4
USB read rc read 64
USB recv: 0000000383000267000300000040021102815a1307551dcbc4764b21b4c4380a8129cd26df0d0e6f9fa6d03e518a8b408a0c7163fdfff06ced3e80d7d2b3acd9
USB data (len 2): 6700
USB send: 000000000383004700010300000040021102815a1307551dcbc4764b21b4c4380a8129cd26df0d0e6f9fa6d03e518a8b408a0c7163fdfff06ced3e80d7d2b3ac
USB write returned 65
USB send: 000000000300db900905c4783c28295b8c9961650000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
USB write returned 65
now trying with timeout 2
now trying with timeout 4
USB read rc read 64
USB recv: 0000000383000267000300000040021102815a1307551dcbc4764b21b4c4380a8129cd26df0d0e6f9fa6d03e518a8b408a0c7163fdfff06ced3e80d7d2b3acd9
USB data (len 2): 6700
USB send: 000000000383004700010300000040021102815a1307551dcbc4764b21b4c4380a8129cd26df0d0e6f9fa6d03e518a8b408a0c7163fdfff06ced3e80d7d2b3ac
USB write returned 65
USB send: 000000000300db900905c4783c28295b8c9961650000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
USB write returned 65
now trying with timeout 2
now trying with timeout 4
USB read rc read 64
USB recv: 0000000383000267000300000040021102815a1307551dcbc4764b21b4c4380a8129cd26df0d0e6f9fa6d03e518a8b408a0c7163fdfff06ced3e80d7d2b3acd9
USB data (len 2): 6700
USB send: 000000000383004700010300000040021102815a1307551dcbc4764b21b4c4380a8129cd26df0d0e6f9fa6d03e518a8b408a0c7163fdfff06ced3e80d7d2b3ac
USB write returned 65
USB send: 000000000300db900905c4783c28295b8c9961650000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
USB write returned 65
now trying with timeout 2
now trying with timeout 4
USB read rc read 64
USB recv: 0000000383000267000300000040021102815a1307551dcbc4764b21b4c4380a8129cd26df0d0e6f9fa6d03e518a8b408a0c7163fdfff06ced3e80d7d2b3acd9
USB data (len 2): 6700
USB send: 000000000383004700010300000040021102815a1307551dcbc4764b21b4c4380a8129cd26df0d0e6f9fa6d03e518a8b408a0c7163fdfff06ced3e80d7d2b3ac
USB write returned 65
USB send: 000000000300db900905c4783c28295b8c9961650000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
USB write returned 65
now trying with timeout 2
now trying with timeout 4
USB read rc read 64
USB recv: 0000000383000267000300000040021102815a1307551dcbc4764b21b4c4380a8129cd26df0d0e6f9fa6d03e518a8b408a0c7163fdfff06ced3e80d7d2b3acd9
USB data (len 2): 6700
USB send: 000000000383004700010300000040021102815a1307551dcbc4764b21b4c4380a8129cd26df0d0e6f9fa6d03e518a8b408a0c7163fdfff06ced3e80d7d2b3ac
USB write returned 65
USB send: 000000000300db900905c4783c28295b8c9961650000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
USB write returned 65
now trying with timeout 2
now trying with timeout 4
USB read rc read 64
USB recv: 0000000383000267000300000040021102815a1307551dcbc4764b21b4c4380a8129cd26df0d0e6f9fa6d03e518a8b408a0c7163fdfff06ced3e80d7d2b3acd9
USB data (len 2): 6700
USB send: 000000000383004700010300000040021102815a1307551dcbc4764b21b4c4380a8129cd26df0d0e6f9fa6d03e518a8b408a0c7163fdfff06ced3e80d7d2b3ac
USB write returned 65
USB send: 000000000300db900905c4783c28295b8c9961650000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
USB write returned 65
now trying with timeout 2
now trying with timeout 4
USB read rc read 64
USB recv: 0000000383000267000300000040021102815a1307551dcbc4764b21b4c4380a8129cd26df0d0e6f9fa6d03e518a8b408a0c7163fdfff06ced3e80d7d2b3acd9
USB data (len 2): 6700
USB send: 000000000383004700010300000040021102815a1307551dcbc4764b21b4c4380a8129cd26df0d0e6f9fa6d03e518a8b408a0c7163fdfff06ced3e80d7d2b3ac
USB write returned 65
USB send: 000000000300db900905c4783c28295b8c9961650000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
USB write returned 65
now trying with timeout 2
now trying with timeout 4
USB read rc read 64
USB recv: 0000000383000267000300000040021102815a1307551dcbc4764b21b4c4380a8129cd26df0d0e6f9fa6d03e518a8b408a0c7163fdfff06ced3e80d7d2b3acd9
USB data (len 2): 6700
USB send: 000000000383004700010300000040021102815a1307551dcbc4764b21b4c4380a8129cd26df0d0e6f9fa6d03e518a8b408a0c7163fdfff06ced3e80d7d2b3ac
USB write returned 65
USB send: 000000000300db900905c4783c28295b8c9961650000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
USB write returned 65
now trying with timeout 2
now trying with timeout 4
USB read rc read 64
USB recv: 0000000383000267000300000040021102815a1307551dcbc4764b21b4c4380a8129cd26df0d0e6f9fa6d03e518a8b408a0c7163fdfff06ced3e80d7d2b3acd9
USB data (len 2): 6700
USB send: 000000000383004700010300000040021102815a1307551dcbc4764b21b4c4380a8129cd26df0d0e6f9fa6d03e518a8b408a0c7163fdfff06ced3e80d7d2b3ac
USB write returned 65
USB send: 000000000300db900905c4783c28295b8c9961650000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
USB write returned 65
now trying with timeout 2
now trying with timeout 4
USB read rc read 64
USB recv: 0000000383000267000300000040021102815a1307551dcbc4764b21b4c4380a8129cd26df0d0e6f9fa6d03e518a8b408a0c7163fdfff06ced3e80d7d2b3acd9
USB data (len 2): 6700
USB send: 000000000383004700010300000040021102815a1307551dcbc4764b21b4c4380a8129cd26df0d0e6f9fa6d03e518a8b408a0c7163fdfff06ced3e80d7d2b3ac
USB write returned 65
USB send: 000000000300db900905c4783c28295b8c9961650000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
USB write returned 65
now trying with timeout 2
now trying with timeout 4
USB read rc read 64
USB recv: 0000000383000267000300000040021102815a1307551dcbc4764b21b4c4380a8129cd26df0d0e6f9fa6d03e518a8b408a0c7163fdfff06ced3e80d7d2b3acd9
USB data (len 2): 6700
USB send: 000000000383004700010300000040021102815a1307551dcbc4764b21b4c4380a8129cd26df0d0e6f9fa6d03e518a8b408a0c7163fdfff06ced3e80d7d2b3ac
USB write returned 65
USB send: 000000000300db900905c4783c28295b8c9961650000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
USB write returned 65
now trying with timeout 2
now trying with timeout 4
USB read rc read 64
USB recv: 0000000383000267000300000040021102815a1307551dcbc4764b21b4c4380a8129cd26df0d0e6f9fa6d03e518a8b408a0c7163fdfff06ced3e80d7d2b3acd9
USB data (len 2): 6700
e0039{"errorCode": 5, "errorMessage":"register:timeout error"}USB send: 00000000038100010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
USB write returned 65
now trying with timeout 2
now trying with timeout 4
USB read rc read 64
USB recv: 00000003810001000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
Checking device USB Receiver.
Usage: 2 UsagePage: 1.
Checking device USB Receiver.
Usage: 2 UsagePage: 1.
Checking device USB Receiver.
Usage: 1 UsagePage: ff00.
Checking device USB-compliant keyboard.
Usage: 0 UsagePage: 0.
Checking device USB-compliant keyboard.
Usage: 0 UsagePage: 0.

**Comment by prefiks** [comment]
Many thanks for help with this.

So it looks like this was not "user didn't press button" message, i really don't know what to do at this point...

**Comment by Vednier** [comment]
Ok. i just decided to test it on Srware Iron 45 (basically rebuilded Chromium 45)

So, its works in Iron on https://demo.yubico.com/u2f, led is blinking, button push registered. Yubiko complains "Unverified device. The type of device you have used is unknown to the server" and returns this technical data (probably nothing interesting)
Anyway, i dunno thats wrong with HyperSecu, but looks like it should work.

Registration Data
origin: https://demo.yubico.com
version: U2F_V2
challenge: pYna18rwQdnhQZloWqVpgdlecPKYKCuvgSJ_QcFb1Gg
appId: https://demo.yubico.com

Response Data
clientData: {"typ":"navigator.id.finishEnrollment","challenge":"pYna18rwQdnhQZloWqVpgdlecPKYKCuvgSJ_QcFb1Gg","origin":"https://demo.yubico.com","cid_pubkey":""}
registrationData: 05041dd139e6cf1cf2bf9d0a76a4cf01d9bceffe08eb7d0e1dd620d0ca982fc40aac083a47a5c42eac9f43d98eba0e7e85d43e6a4dd329be9aac0cd7f8f1f526a82c408747bd57e8d911189bdc6e6cab001e7380262f1676cf90f2903b4eb61915675d92acc314e3eb4f38450f96726a7f421b51b26a2e227f1788bc3c7cdf27ec6df03082013c3081e4a003020102020a42355764645193539529300a06082a8648ce3d0403023017311530130603550403130c4654204649444f2030313030301e170d3134303831343138323933325a170d3234303831343138323933325a3031312f302d0603550403132650696c6f74476e756262792d302e342e312d34323335353736343634353139333533393532393059301306072a8648ce3d020106082a8648ce3d030107034200041dd139e6cf1cf2bf9d0a76a4cf01d9bceffe08eb7d0e1dd620d0ca982fc40aac083a47a5c42eac9f43d98eba0e7e85d43e6a4dd329be9aac0cd7f8f1f526a82c300a06082a8648ce3d0403020347003044022090d47240d72a090a7b9bbf2aba3386705045dc8f1ad0b6d6cc7bc7d6a62c0f620220b3ca08455ec4cc229e548415c23b0445ab2895f90705311de4a457beab8efd2430450220594adedaebd7fcde201205b33767eca5f8a400571f10f5f43d4239f7e7487f48022100ff7625a5ea8a818249c656ad9ff25335def790d67fd863052128b9159fa0c0bf

Attestation Certificate
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            42:35:57:64:64:51:93:53:95:29
    Signature Algorithm: ecdsa-with-SHA256
        Issuer: CN=FT FIDO 0100
        Validity
            Not Before: Aug 14 18:29:32 2014 GMT
            Not After : Aug 14 18:29:32 2024 GMT
        Subject: CN=PilotGnubby-0.4.1-42355764645193539529
        Subject Public Key Info:
            Public Key Algorithm: id-ecPublicKey
                Public-Key: (256 bit)
                pub: 
                    04:1d:d1:39:e6:cf:1c:f2:bf:9d:0a:76:a4:cf:01:
                    d9:bc:ef:fe:08:eb:7d:0e:1d:d6:20:d0:ca:98:2f:
                    c4:0a:ac:08:3a:47:a5:c4:2e:ac:9f:43:d9:8e:ba:
                    0e:7e:85:d4:3e:6a:4d:d3:29:be:9a:ac:0c:d7:f8:
                    f1:f5:26:a8:2c
                ASN1 OID: prime256v1
    Signature Algorithm: ecdsa-with-SHA256
         30:44:02:20:90:d4:72:40:d7:2a:09:0a:7b:9b:bf:2a:ba:33:
         86:70:50:45:dc:8f:1a:d0:b6:d6:cc:7b:c7:d6:a6:2c:0f:62:
         02:20:b3:ca:08:45:5e:c4:cc:22:9e:54:84:15:c2:3b:04:45:
         ab:28:95:f9:07:05:31:1d:e4:a4:57:be:ab:8e:fd:24
-----BEGIN CERTIFICATE-----
MIIBPDCB5KADAgECAgpCNVdkZFGTU5UpMAoGCCqGSM49BAMCMBcxFTATBgNVBAMT
DEZUIEZJRE8gMDEwMDAeFw0xNDA4MTQxODI5MzJaFw0yNDA4MTQxODI5MzJaMDEx
LzAtBgNVBAMTJlBpbG90R251YmJ5LTAuNC4xLTQyMzU1NzY0NjQ1MTkzNTM5NTI5
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEHdE55s8c8r+dCnakzwHZvO/+COt9
Dh3WINDKmC/ECqwIOkelxC6sn0PZjroOfoXUPmpN0ym+mqwM1/jx9SaoLDAKBggq
hkjOPQQDAgNHADBEAiCQ1HJA1yoJCnubvyq6M4ZwUEXcjxrQttbMe8fWpiwPYgIg
s8oIRV7EzCKeVIQVwjsERasolfkHBTEd5KRXvquO/SQ=
-----END CERTIFICATE-----

**Comment by prefiks** [comment]
Ok i found this: https://github.com/Manouchehri/HyperFIDO/ which contains usb dumps from working registration session, will see if i would be able to figure out something from those.

**Comment by Vednier** [comment]
If you provide me instruction i can get you any dump you may need too. Probably wireshark and stuff.

**Comment by prefiks** [comment]
Thanks, if/when i would need something, will know who ask for them :)

**Comment by prefiks** [comment]
Hello, i did receive device that did generate similar logs to those that you attached in this ticket. In version 0.0.8 that was recently published i made changes that made my device work on firefox, hopefully those modification will help your device as well.

**Comment by Vednier** [comment]
Ok, i just got to be able to test it (0.0.10) - its works (both register and login)! Many thanks!!!!
Now i need to test it on custom real setup and i guess thats it.
