### ISSUE TITLE
U2F Support addon 0.0.2 cause severe perfomance degradation and all sort of weird bugs

### ISSUE THREAD

**Issue by Vednier** [prefiks/u2f4moz#12]
Ok, just things i see
On installation Firefox hangs  for aprox 30 sec.
There is unresponsible script warning appears too.
After installation Firefox periodically suggests to uninstall or disable addon.
About:perfomance shows that it "may currently be slowing down Nightly".
Now to even better part - after forced disabling of addon Firefox starting to work weird - most noticeable glitches - inability to switch tabs (errors about system scripts undefined in error console), breakage of NoScript - no script button become defunct, script state cannon be changed, enable or disabled.  
Firefox restart solves glitches.
Yes, i understand its early alpha and its just not ready.

**Comment by prefiks** [comment]
I must say i don't have this issue with release or nightly version of firefox (and i am using electrolysis on nightly version). Maybe bad interaction with some other extension?

Now that i think about it, maybe this is a result of adding code adding u2f object to existing pages, could you tell me more or less how much tabs do you have open in your firefox?

**Comment by Vednier** [comment]
Around 1000...

**Comment by prefiks** [comment]
Ok, it may be this part then. I will test how this work with using flag that is making u2f object only available in freshly loaded pages and will probably publish that change in new version if everything will be ok.

**Comment by prefiks** [comment]
Version 0.0.3 that was recently published have a tweak that hopefully will help with many tabs problem, i did limited testing and it appears to work better now.

**Comment by Vednier** [comment]
Yes. i retested it
1) No more hangs on installation
2) No more Unresponsible script warnings
3) about:performance looks fine
4) No more glitches on disable\uninstall
