### ISSUE TITLE
Show message to user that device should be plugged in

### ISSUE THREAD

**Issue by prefiks** [prefiks/u2f4moz#21]
Binary part now delivers information about missing device, we probably should have some kind of notification message to user about this. Maybe it could be shown in a similar way to notification that ask about enabling plugin at page?

**Comment by mnoorenberghe** [comment]
I was just looking at this and at the add-on SDK APIs and it seems like there isn't an API for that now and requiring "chrome" slows down addons.mozilla.org review… we could use the notification API instead which opens a notification outside the browser window.

**Comment by mnoorenberghe** [comment]
I have a working patch using the SDK's notification API which may be okay as-is but there is a bug in the SDK (at least on OS X) that the notification doesn't close upon click and there is no close API. See 7074db7870987e32f2c7ce76e26c884e7cd7e422 and merge if you think it's good enough as a start.

**Comment by prefiks** [comment]
I checked your implementation in action, and indeed having those notifications be persistent is definitely no ideal user experience. I will probably merge it if something better wont materialize.
