### ISSUE TITLE
Github isn't standards-compliant

### ISSUE THREAD

**Issue by tsjost** [prefiks/u2f4moz#23]
Github is using `u2f.WrappedChromeRuntimePort_` in its integration, which as far as I can tell is not available in the [U2F specification](https://fidoalliance.org/specs/fido-u2f-javascript-api-ps-20150514.pdf), i.e. platform dependent, and they also seem to be browser sniffing.

They have explicitly expressed a desire to _not_ be standards-compliant. From email:

> We are deliberately only supporting browsers that natively have support for the U2F protocol.
> We'll update our support as other browsers get native support for U2F.

Would it be a good idea to implement a work-around (until Firefox gets native support) or somehow encourage them to write proper code?

**Comment by prefiks** [comment]
That sucks. I looked briefly at having some kind of workaround for this, but didn't found anything particular easy to have extension working with github. Probably will try to prepare something that will closer mimic interface exposed by chrome, but this needs a bit of work.

**Comment by Tijojo** [comment]
I think I have a similar issue with Google account.
When changing the user agent, I have a "Chrome Extension not found" error and a link to https://chrome.google.com/webstore/detail/gnubbyd/beknehfpfkghjoafdifaflglpjkojoco .
Else it work well on https://demo.yubico.com/start/u2f/neo (just an error saying I need Chrome 41 but it can be ignored).

Nice work by the way !

**Comment by mnoorenberghe** [comment]
According to a GitHub employee at https://bugzilla.mozilla.org/show_bug.cgi?id=1065729#c112 the extension works on GitHub now.

**Comment by prefiks** [comment]
Yes it looks like it's working now, at least i was able to login with my device.
