### ISSUE TITLE
Won't install on Firefox 42.0 Stable 64-bit

### ISSUE THREAD

**Issue by ofsaleem** [prefiks/u2f4moz#25]
Says that it's not compatible with 42.0, despite the page saying 43 is supported. Took a look at the install.rdf and saw that there was no 64-bit version listed. Edited it to allow 64 bit install, installed the addon, and it didnt seem to work.

**Comment by prefiks** [comment]
Did it hit this problem on 64-bit Windows?

**Comment by prefiks** [comment]
I just published version 0.0.6 of this add-on that hopefully should fix problem with 64-bit firefox on windows
