### ISSUE TITLE
Please consider putting (symlink to or) install.rdf file in root of repo.

### ISSUE THREAD

**Issue by ghost** [prefiks/u2f4moz#26]
Fantastic extension. Thank you so much!
Sadly Firefox does not auto-update as extension has not been approved (yet). As it's a security thing I'd rather have the latest and I keep forgetting to check.

Per [GitHub Extension Installer](https://addons.mozilla.org/en-US/firefox/addon/github-extension-installer/?src=search) : _"extension files are placed in the root of the repo. If that is the case (ie, a install.rdf file is found there), a new button will be added in the right-bottom side of the page as shown on the screenshot."_

**Comment by prefiks** [comment]
Looks like this extension requires to have extension code directly in root folder of repository (aka everything that is inside ext/ will need to be put in root of repository), additionally binary parts used to talk to usb device (that are compiled for different platforms from content of c_src) aren't part of this repository, so in current version it wouldn't be possible to generate xpi from content from this repo by just zipping all files from it.

I will try to deploy server serving auto-update information for this extension, at least until this get accepted by AMO.

**Comment by prefiks** [comment]
Auto-updates are now live, but you would probably need to install xpi from https://github.com/prefiks/u2f4moz/releases/download/v0.0.6/u2f-0.0.6-github.xpi (this version has informations pointing to update url).

**Comment by ghost** [comment]
Oh that's great, thank you! Very speedy response too (unlike mine, sorry!).

Testing! Testing!

**Comment by ghost** [comment]
All good. No problems experienced, and auto-updates.
