### ISSUE TITLE
Addon needs to be signed to be installable on Firefox 43 and later

### ISSUE THREAD

**Issue by sdaugherty** [prefiks/u2f4moz#28]
https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox?as=u&utm_source=inproduct

Please create a signed version of the XPI.

**Comment by prefiks** [comment]
I am fully aware of this, i submitted this extension for AMO staff review that is required for this, couple weeks ago, it's currently 26 in queue for review.

**Comment by prefiks** [comment]
And latest version of add-on just got reviewed, and as such got signed by Mozilla.
