### ISSUE TITLE
Linux/FF 44.0.2 + Yubikey Neo + Yubico Demo fails

### ISSUE THREAD

**Issue by iam-TJ** [prefiks/u2f4moz#30]
Testing 0.0.13 with a Yubikey Neo on Linux with Firefox 44.0.2 at the https://demo.yubico.com fails with a time-out. The console shows:

TypeError: ({register:function register() {
    [native code]
}, sign:function sign() {
    [native code]
}}) is not extensible
 u2f-api.js:23:1
The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must be declared in the document or in the transfer protocol. u2f
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead. jquery-1.8.3.min.js:2:40351

**Comment by iam-TJ** [comment]
0.0.11 does work, as reported by "Dylan" in the a.m.o review of 8th February

**Comment by prefiks** [comment]
What OS are you using? windows/mac/linux?

**Comment by iam-TJ** [comment]
As the issue states, Linux. Specifically, Ubuntu 15.10 x86_64 with the Yubico PPA

**Comment by iam-TJ** [comment]
After some extensive testing with permutations of my own builds and the a.m.o XPI, removing, restarting browser, installing, restarting browser, testing, somehow the issue has gone away and I cannot reproduce it.
I was able to reproduce it about 30 times with various test scenarios until it began behaving.

Whilst the issue was still occurring I tested the v0.0.13 tag with commit ef48de4 reverted and it would work. I then installed the a.m.o v0.0.13 XPI, verified it failed, then copied the 'git revert' version of ext/index.js into the installed Firefox extension and it worked.

That seemed to confirm the issue is with the changes in commit ef48de4.

 If the issue recurs I'll report back.

**Comment by iam-TJ** [comment]
Tested with a new, empty, profile. Installed v0.0.13 from a.m.o., visited https://demo.yubico.com/u2f and tested: it works.

I wonder if some kind of race condition with the worker and external helper caused this?

**Comment by prefiks** [comment]
Yes, it's most likelly some kind of problem with interaction between binary and js part driver code. I still was not able to reproduce this, but maybe i finally would be able to do it.

**Comment by iam-TJ** [comment]
Currently reproducing the issue in my primary Firefox profile without having reinstalled. It recurred after the demo.yubico.com site appeared to be rebooted. Trying to register an account there is no U2Fmoz prompt and it times out.

Possibly associated and a clue is that the page reports the error:

This demo requires Chrome 41 or later!
Your current browser is not yet supported.

which it doesn't do when u2fmoz is working correctly. Does this point to some kind of activation/page-attach issue?

I used 'inotifywait' to monitor accesses to the extension's directory and all appears correct:

https://iam.tj/projects/misc/u2f-inotify.log.txt

Any tips on how I can actively debug this for you?

**Comment by prefiks** [comment]
I have this text always displayed in firefox, no matter if plugin works or not, so this rather not tells anything.

You probably would be able to get some information from extension by enabling extensions debugging. It's not very straightforward, but it shouldn't break anything on your browser.

You can do this by opening webconsole (ctrl+shift+i does it for me) and after clicking on gear icon in advanced settings toggling "Enable browser chrome and add-on debugging", This should add "Debug" button in add-on manger, clicking on it should open console for choosen extension.

It may be also needed to add extra preference in about:config page, after loading it right click on it and select "New > String" use "extensions.u2f4moz@prefiks.org.sdk.console.logLevel" as name and "all" as value.

**Comment by iam-TJ** [comment]
I've just been running it through the browser debugger, with chrome debugging and remote enabled. I _may_ have firmed up on the earlier  console TypeError message (although I'm not sure if that is related to this issue).

data/content-script.js defines the 'u2f' array object. The demo.yubico.com/u2f-api.js also has

var u2f = u2f || {};

and that's the line that throws the TypeError.

It rather looks as if there's some kind of issue there with the name clash. I'll try altering the extension's var-name.

**Comment by prefiks** [comment]
This extension exposes window.u2f object to webpage, as interface for accessing u2f functionality, please don't change it inside extension, this will not help in making it working.

Chrome doesn't offer this, so for it webpage use js helper library that simulates it, but this should work with window.u2f from firefox extension

**Comment by prefiks** [comment]
Can you also tell me what you get in webconsole on u2f demo page when you type window.u2f or u2f or window.u2f.register+"" ?

**Comment by iam-TJ** [comment]
window.u2f doesn't exist when trying to do the registration

**Comment by iam-TJ** [comment]
Right, single-stepped through from data/content-script.js defining the 'u2f' object to a breakpoint on line 23 of u2f-api.js. At this point the object is still correct.

As soon as that line is single-stepped the TypeError exception occurs, the script stops executing, and the page shows the "Performing U2F action" modal dialog.

**Comment by iam-TJ** [comment]
From what I'm reading adding 'u2f' to the extension's 'self' object will prevent altering it later as the extension's 'self' object is sealed so you can't add properties to it.

**Comment by prefiks** [comment]
Yes, it is here to prevent modification by chrome compatibility layer from u2f-api.js

**Comment by prefiks** [comment]
I wonder why this works like that on your browser and works without problems here...

**Comment by iam-TJ** [comment]
Not sure! It doesn't solve the missing u2fmoz functionality though. I commented out the data/content-script.js "Object.freeze(u2fOnPage)" and that avoids the TypeError though.

I now see window.u2f.register == function register()

I'll try debugging further.

**Comment by iam-TJ** [comment]
Tracing the 'register' functionality.

index.js::execBin() is called, which reaches the line 89 call

```
_execBin(event, origin, ch, null, callbackid, worker, timeout);
```

but the breakpoints in _execBin() never fire, which suggests the function call fails.

The tracing shows some kind of internal (SDK?) processing of promises. I've not found an easy way, so far, to get the debugger to dump/log to text the call-stack etc. in order to show where it gets to.

**Comment by iam-TJ** [comment]
Linked is a debugger screenshot of a stack trace captured just after the unexecuted call to _execBin() on line 89. To the right you can see the breakpoints. The B.P. on line 94 in _execBin() never fired.

https://iam.tj/projects/misc/u2fmoz-stack-01.jpg

I was reading about the Promises and found references that say that 'sdk/core/promise' and promise.Defer() is obsolete and should be replaced with 'promise' and alternate code, and there's some interesting discussion and explanation as to the difference instances and timing-related problems (in unit tests, for example). See for example:

https://bugzilla.mozilla.org/show_bug.cgi?id=1196714 "Convert sdk/core/promise require to require(promise) in devtools codebase"
https://bugzilla.mozilla.org/show_bug.cgi?id=1195825 " Import promise.jsm via require(promise) in devtools codebase"
https://developer.mozilla.org/en-US/docs/Mozilla/JavaScript_code_modules/Promise.jsm/Deferred "Promise.jsm::Deferred"

**Comment by iam-TJ** [comment]
I hit a very weird situation which might be related to the issue. In execBin() I extended the 'else'  clause to be a {...} block and added a 'console.info()' statement. During debugging, despite a breakpoint on that statement, and whilst single-stepping, Firefox completely passed over it. I then added another nine identical statements and Firefox passed over all of them.

It also passed over the call to _execBin().

Just as I thought I was getting somewhere it began working correctly again! Between each code-change the Firefox testing profile just for u2fmoz is stopped and started.

console.info: u2f: execBin() enter
console.info: u2f: execBin() calling _execBin(no-check-sign)
console.info: u2f: EB1 sign https://demo.yubico.com Array [{"challenge":"TDY2sFf7KWWvc2QR2UqgrZ7UkcEwvwousZgW3ud5rCU","version":"U2F_V2","keyHandle":"DsomF97jnN4yqgf5S2XO2SXdFlU2zUShw_drO3Fs7NR9Nbs8Y-o-BbZeX5kmq0ftUH5LiKioFb5FYTn1lqoBRg","appId":"https://demo.yubico.com"}] null
console.info: u2f: EB2 /home/tj/.mozilla/firefox/osv3ekte.U2F/extensions/u2f4moz@prefiks.org/bin/linux_x86_64-gcc3/u2f
console.info: u2f: EB3 constructor {"killed":false,"stdin":{"readable":false,"writable":false,"encoding":null},"stdout":{"readable":false,"writable":false,"encoding":null},"stderr":{"readable":false,"writable":false,"encoding":null}}
console.info: u2f: stdin s0017000100d5https://demo.yubico.com{"challenge":"TDY2sFf7KWWvc2QR2UqgrZ7UkcEwvwousZgW3ud5rCU","version":"U2F_V2","keyHandle":"DsomF97jnN4yqgf5S2XO2SXdFlU2zUShw_drO3Fs7NR9Nbs8Y-o-BbZeX5kmq0ftUH5LiKioFb5FYTn1lqoBRg","appId":"https://demo.yubico.com"}
console.info: u2f: EBD b
console.info: u2f: device waits for button press
console.info: u2f: execBin() leave
console.info: u2f: EBD r01b0{ "signatureData": "AQAAABIwRgIhAOl8tptEnQI-sXFD8AVBPs8wcA_f4KoNuTAGfHGoEsMcAiEA4PqwnranI9NLr5JsmQnbA35KvXqERkRAzLiHc_SN6-I=", "clientData": "eyAiY2hhbGxlbmdlIjogIlREWTJzRmY3S1dXdmMyUVIyVXFnclo3VWtjRXd2d291c1pnVzN1ZDVyQ1UiLCAib3JpZ2luIjogImh0dHBzOlwvXC9kZW1vLnl1Ymljby5jb20iLCAidHlwIjogIm5hdmlnYXRvci5pZC5nZXRBc3NlcnRpb24iIH0=", "keyHandle": "DsomF97jnN4yqgf5S2XO2SXdFlU2zUShw_drO3Fs7NR9Nbs8Y-o-BbZeX5kmq0ftUH5LiKioFb5FYTn1lqoBRg" }
console.info: u2f: exit 0 null

**Comment by prefiks** [comment]
Ah so at least you got your window.u2f object visible from webpage, did you had to do something special for this or it just started working?

**Comment by iam-TJ** [comment]
I triggered it again and I think I've spotted what is going on. It _looks_ as if 'checkSignChallenges' is sometimes a valid object but has 0 (array) elements, causing the wrong code branch to be followed.

After applying the patch linked below it - so far - seems to be behaving predictably.

https://iam.tj/projects/misc/u2f-index.js.patch.txt

line 74 is the key; the other code is to ensure I can trace the execution path without the debugger (in case the debugger is causing some additional problems)

**Comment by prefiks** [comment]
Good catch, care to prepare pull request?

**Comment by iam-TJ** [comment]
Let's wait until I can be 100% certain the 'fix' is real and not just the browser still flipping between good and bad sessions.

Earlier I noticed that once a registration had been successful once it seemed to work correctly for quite some time. I've got 2 registrations on demo.yubico.com and am currently testing with "Login" rather than "Register".

**Comment by prefiks** [comment]
I think this is correct change, maybe there is another problem that you hit, but that change should help with some cases.

**Comment by iam-TJ** [comment]
I wonder if the issue could be indirectly due to delayed Garbage Collection and a weak reference remaining to an already-used checkSignChallenges object.

**Comment by prefiks** [comment]
This is a problem with allValid() from appIdValidator, it doesn't handle empty arrays correctly, if it gets one it never calls finished and that make it never call resolve() on promise that this function returns. Place that uses it never finish waiting for promise to finish and it leads to timeout.

**Comment by iam-TJ** [comment]
I did wonder about that when I was tracing the Promise logic but I couldn't keep track of all the objects well enough - I thought at some points resolve() didn't execute, or a reject() occurred that wasn't caught anywhere.

I'll let you formulate the fix since there's clearly more than a simple Array.length check required. I can either pull directly from a test branch on github or apply a patch file to test it.

**Comment by prefiks** [comment]
Change commited, seems to work in my tests

**Comment by iam-TJ** [comment]
That does seem to have solved it, thanks very much.
