### ISSUE TITLE
Won't work in Firefox 45.0.x, Linux x64

### ISSUE THREAD

**Issue by JSkier21** [prefiks/u2f4moz#35]
Can't seem to get this to work on two Linux boxes, Firefox 45 x64. Updated udev permissions and rebooted. Works fine in Chrome.
GitHub says browser isn't supported when I try to force it, other sites (WP, Google), wonn't even consider the option of u2f. 

Using a couple yubikey4 devices, Version 0.0.16 of plugin (will try to compile next). 

> Kernel: 4.4.5-1
> local/yubico-c 1.13-2
>     Yubico YubiKey C library
> local/yubico-c-client 2.15-1
>     Yubico YubiKey client C library
> local/yubico-pam 2.21-1
>     Yubico YubiKey PAM module
> local/yubikey-personalization 1.17.3-1
>     Yubico YubiKey Personalization library and tool
> local/yubikey-personalization-gui 3.1.24-1
>     Yubico YubiKey Personalization GUI

**Comment by prefiks** [comment]
Please make sure you don't have chrome opened when you trying this, chrome takes exclusive access to device. I don't test yubikey4 as i don't have it, but i belive it should be working with it.

**Comment by JSkier21** [comment]
Chrome wasn't open, I did see that before. 

Also, compiled source, same version as what Mozilla is hosting, but tried it anyway, same issue.

**Comment by prefiks** [comment]
I am working on adding simpler way to get logs from extension, maybe with that it would be possible to figure out what's going on.

It's possible to get logs from extension right now but it's not that straightforward (it requires enabling extension debugging, and tweaking some options in about:config) but it may be a better idea to wait for when i finish this, probably today or tomorrow.

**Comment by prefiks** [comment]
I just published version 0.0.17 that has show log option added (in addon panel clicking on preferences button on u2f extension should show panel with "Show Logs" button).

This version also did made GitHub again detect u2f capability after changes that were made on GitHub to code responsible for that in last couple days, so it's likelly that this version will work correctly for you - if not i would be grateful for copy/pasting logs after unsuccessful try to use u2f device.

**Comment by JSkier21** [comment]
In Firefox, I have to elect to use the key option in GitHub now (whereas Chrome it is primary). It works though, thanks for being so quick on this!

Google and Wordpress don't work at all; log file won't even mention anything. I'll try switching the user-agent to see if I can work around it somehow.

**Comment by JSkier21** [comment]
I will close this, thank you again. User agent tricks wordpress and it works, also defaults with GitHub. Google thinks it's faked Chrome browser is missing an extension and won't work. I see there is a separate issue for Chrome, I'll add to that.

**Comment by prefiks** [comment]
There is #24 for tracking problem with Google
