### ISSUE TITLE
retry after timeout

### ISSUE THREAD

**Issue by My1** [prefiks/u2f4moz#37]
as already stated in my Reviews: after getting a timeout, a retry (sending the same U2F request again results in another timeout even if the U2F device was properly activated.

This is the last problem that I saw with U2F in firefox.

when you push this problem into oblivion it would be really epic.

**Comment by prefiks** [comment]
Your logs is showing that binary part was executed correctly and it's waiting for plugging in device into usb port. Do you by chance have chrome running when that happens? It block access to u2f device when it's active.

**Comment by My1** [comment]
well I dont know what the logs say (I dont even know where to find them) but at least the popup asking for the U2F device comes propery (the one close to the URLbar) also I mostly dont run chrome, also, I may have forgotten but a whole refresh of the site fixes the whole problem.

**Comment by prefiks** [comment]
Ups, sorry i did mistake your ticket with #36 that i got notification at this same time and my comment was related to that one.

I was able to track that issue and i have fix for it, it will be fixed in next release.

**Comment by My1** [comment]
that is nice to know

**Comment by prefiks** [comment]
And version 0.0.18 that i just released have fix for this.

**Comment by My1** [comment]
and we can wait day after day until mozilla signs it coz of their stupid requirement.

**Comment by My1** [comment]
well anyway. seems the "I dont care about signatures" option is still there. confirmed working with github, I will try others when I get the chance.
