### ISSUE TITLE
Doesn't work with Dropbox and U2F website

### ISSUE THREAD

**Issue by Crocmagnon** [prefiks/u2f4moz#42]
Hello,
I have troubles getting the extension to work with Dropbox. It works fine on GitHub (though I have to click on "Use security key" when asked to enter authenticator code).

Here's my setup :
- macOS Sierra (10.12) public beta
- Firefox 47.0.1 (up to date)

Other machine, same behavior :
- Fedora 24 (up to date)
- Firefox 47.0 (up to date)
- `.rules` file installed (works with GitHub)

Both have same version of extension : 0.0.19, from Firefox "store"

The u2f website also doesn't like it, here is a screenshot :
![Screenshot](https://www.dropbox.com/s/xe6pd9yy2i4i2ym/Capture%20d%E2%80%99%C3%A9cran%202016-07-12%20%C3%A0%2022.46.46.png?raw=1)

I tried to view the logs but the extension doesn't seem to be called, it only shows entries related to GitHub.

**Comment by Crocmagnon** [comment]
By the way, I'm quite proud of opening issue #42 ! 😄

**Comment by Crocmagnon** [comment]
I tested under Fedora 24, updating the original post.

**Comment by prefiks** [comment]
Hello,

Dropbox, checks what user-agent is sent by browser and sends code for u2f handling only if it detects Chrome. If i remember correctly if you changed user-agent in Firefox to presents itself as Chrome, then you were able to register/sign using your u2f key.

Same situation with demo page, it checks if your browser is Chrome and if not shows that message.

**Comment by Crocmagnon** [comment]
I thought only Google did that on their authentication pages :/
It seems like a duct tape workaround, isn't there really any better solution ?

If not, how should I change my user agent to present it as Chrome ?

I can see on the review page of your extension in Firefox modules that it works with Dropbox for [this guy](https://addons.mozilla.org/fr/firefox/addon/u2f-support-add-on/reviews/802679/). Do you have more information ?

**Comment by prefiks** [comment]
You could use extension like that one: https://addons.mozilla.org/pl/firefox/addon/user-agent-switcher/ it should allow you to change your user-agent.

**Comment by Crocmagnon** [comment]
Ok, I confirm it works when changing the user agent. But it kinda s*cks that some devs implemented it like only Chrome could support U2F...

**Comment by mnoorenberghe** [comment]
Please report this to the authors of the sites. They should be doing feature detection instead of using UA sniffing for this.

**Comment by Crocmagnon** [comment]
Yes obviously, I didn't expect @prefiks to change Dropbox code 😉

So if there is no better solution than presenting Chrome's user agent, maybe we could close this issue ?

**Comment by mhalano** [comment]
@Crocmagnon Did you report the bug to Dropbox? May be report and post the status in this issue until become fixed.

**Comment by KellerFuchs** [comment]
@Crocmagnon @mhalano Should this issue be closed?  (This doesn't prevent @Crocmagnon from comenting once websites get fixed)

**Comment by mhalano** [comment]
Sure. Why not? 

On Sep 30, 2016, The Fox in the Shell notifications@github.com wrote:

> @Crocmagnon @mhalano Should this issue be closed?  (This doesn't
> prevent @Crocmagnon from comenting once websites get fixed)

## 

Sent with <a href="https://play.google.com/store/apps/details?id=com.onegravity.k10.pro2"><b>K-@ Mail</b></a> - the evolution of emailing.
