### ISSUE TITLE
Extension now blocked because extension isn't signed

### ISSUE THREAD

**Issue by bmillemathias** [prefiks/u2f4moz#44]
as of today I'm notified the extension can't be used anymore because it COULD be insecure.
So I'm redirected to https://support.mozilla.org/1/firefox/49.0.1/WINNT/fr/unsigned-addons.

**Comment by prefiks** [comment]
Hello, did you install this extension from https://addons.mozilla.org/firefox/addon/u2f-support-add-on/ ?

**Comment by bmillemathias** [comment]
Let's close this issue, I hve strange behaviour caused because I'm not administrator of the machine (I don't know it this case worth a bug).
