### ISSUE TITLE
Support for version 1.1 of the API seems missing

### ISSUE THREAD

**Issue by elouet** [prefiks/u2f4moz#45]
The way I understand this extension's code is that it is not compatible with applications expecting FIDO U2F version 1.1 API (passing a single appID/challenge and multiple keyHandles in the same call). 
This makes website development more difficult, because the code to run on Chrome and Firefox will have to be different.

**Comment by prefiks** [comment]
Indeed looks like current version doesn't handle that properly, i will try to add that to next version.

**Comment by raupachz** [comment]
I just tried with FIDO U2F version 1.1 API and the add-on works. Used the u2-api.js from Google. https://github.com/google/u2f-ref-code/blob/master/u2f-gae-demo/war/js/u2f-api.js

**Comment by prefiks** [comment]
I forgot that i added compatibility code for 1.1 version some time ago, current version should be able to accept both old and new call signatures to u2f.sign and u2f.register.
