### ISSUE TITLE
Interfering with Google Docs

### ISSUE THREAD

**Issue by medicalwei** [prefiks/u2f4moz#46]
It is currently interfering with Google Docs and I cannot load Google Spreadsheets when this add-on is switched on.

Error in Console

```
TypeError: can't redefine non-configurable property u2f
```

**Comment by prefiks** [comment]
This should be fixed by commit 77dfc60bcbc492f040187d1aa647fe049b5aa2d5

**Comment by prefiks** [comment]
This problem will be fixed by version 1.0 of extension that i just released.
