### ISSUE TITLE
Does not work with U2F tokens without confirmation button

### ISSUE THREAD

**Issue by keppler** [prefiks/u2f4moz#6]
Under Windows 7, the add-on works absolutely fine with a "FIDO U2F Security Key" from Yubico.
But when using a U2F token without button (in this case a low-cost token from [Plug-Up/Happlink](http://sk.happlink.com/plugup/en/)), the "errorCode: 1" is immediately returned.
Chrome displays a message like "please insert your U2F device" when a registration is requested but no device is present. With the low-cost tokens (without confirmation button), the confirmation is signalled by inserting the device into the USB port (after inserting, the device is ready for registration for some seconds).

If you like I can send you such a low-cost FIDO token for free (just need your postal address).

And of course THANK YOU for your great work! :)

**Comment by prefiks** [comment]
Just published version 0.0.3 will wait for device to be plugged in, will you be able to check if this version works correctly with this device?

**Comment by keppler** [comment]
Successfully tested (FF 41.0.2, Windows 7)! :) Great work!
