### ISSUE TITLE
U2F enabled by default on Yubikeys "effective November 2015"

### ISSUE THREAD

**Issue by cdokolas** [prefiks/u2f4moz#60]
In the `README.md` file and section "Enabling U2f on Yubico Neo and Neo-n", you mention that "Those two devices don't have U2F enabled by default". This is not true anymore (look at the document you link to). It would be great if you changed this section to apply to pre-Nov'15 Yubikeys so new Yubikey owners will not have useless adventures.

Thanks.

**Comment by inputsh** [comment]
This can be closed now. :)
