### ISSUE TITLE
Ext no longer working after update to windows 1903 (May 2019)

### ISSUE THREAD

**Issue by Interghost** [prefiks/u2f4moz#63]
Hi, 

I realize this is a turbo long shoot :) since this is not maintained/obsolete, but I've been a very happy user of your ext on SeaMonkey (based on Firefox but stuck at older engine)... however after update to Windows 1903 it stopped working.
When I initiate u2f login it just says please plug in your key... as if not detecting it (and it is plugged in)... any chance you could help?

**Comment by prefiks** [comment]
Hello,

I am guessing the u2f.exe that is included in this extension stopped working, or possibly extension no longer can locate it, possibly some information will be in logs for this extension (in firefox there was a button in preferences pane of that extension, that did open window with logs), could you check if you can access that and possibly show it here after unsuccessful operation?

**Comment by Interghost** [comment]
Thank you for the reply!

I managed to make some progress... it appears the issue is u2f.exe has to be "run as administrator". So it works normally if I start the browser with Run as administrator, which I'd rather not do...  trying to figure out how to add u2f.exe to a safe list or something to always run as admin without the UAC prompts

**Comment by prefiks** [comment]
No idea unfortunately, this program talks to your token over usb, possibly microsoft did made some extra restrictions to programs that try to access hardware?
